services:
  - type: web
    name: aura-trades-api
    runtime: python
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 600
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: RENDER
        value: "1"
